name: image-utils
channels:
  - conda-forge
  - defaults
dependencies:
  - noise
  - numpy
  - pillow
  - python
  - pip
  - scipy
  - scikit-image
  - pip:
      - opencv-python
      - tifffile==2020.9.3
      - suffix-trees
